{"name": "Double courier creation test", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <test_create_courier.TestCreateCourier object at 0x106810770>, delete_courier = <function delete_courier.<locals>._delete_courier at 0x10683e520>\n\n    @allure.title('Double courier creation test')\n    @allure.description('Double courier creation negative check')\n    def test_create_double_courier(self, delete_courier):\n        payload = Courier('kotik_kotik', 'mur_mur_mur', 'Gershman')\n        (_data, _status_code) = CourierClient().create_courier(payload)\n        (data, status_code) = CourierClient().create_courier(payload)\n    \n        assert status_code == requests.codes['conflict']\n>       assert data['message'] == 'Этот логин уже используется'\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntests/test_create_courier.py:29: AssertionError"}, "description": "Double courier creation negative check", "start": 1707057627027, "stop": 1707057627432, "uuid": "92792f79-cfd3-45a5-81dd-0132e91298c2", "historyId": "e9b504aeddfb364a12068e7ed78b8bef", "testCaseId": "e9b504aeddfb364a12068e7ed78b8bef", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_double_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "Air-Uchiru-5.lan"}, {"name": "thread", "value": "49795-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}